project = "loblaw-health-1"
short_project_prefix = "loblaw-healthcare-t3"
user = "doaa.altarawy@loblaw.ca"
env = "dev"
region = "us-central1"
publickeypath = "~/.ssh/id_rsa.pub"
endpoint = "3388836673805615104"
model = "bart-large-mnli"